### ISSUE TITLE
indicate which repo is current

### ISSUE THREAD

**Issue by foobarbecue** [jmespadero/coindesigner#2]
Hello, I see the source code for coindesigner in three places:

1. https://sourceforge.net/projects/coindesigner/
2. https://github.com/jmespadero/coindesigner/ (this repo)
3. https://github.com/iocroblab/coindesigner/

It looks like 3. is more recent than this one. I'm assuming sourceforge user jespa, who owns the original sourceforge repo, is @jmespadero . That person seems to be involved in both 2 and 3, but 3 has more recent commits.

Could we decide between 2 and 3 which is the active repo and archive the other one or add a note in the readme?

**Comment by jmespadero** [comment]
Yeah, I'm the original author of coindesigner and moved the repository from sourceforge to github.
The project were stalled due the library Coin3D, which is the backend of the project, was also stalled by the company that maintained it. 
Currently I am not doing active changes as today I do most of the work using other software. 

The iocroblab Coindesigner seems to be a fork of the **sourceforge repository** and I haven't notice about their commits. I suposse they are necessary changes to compile coindesigner on modern C++ compilers. Or maybe they have fixed some bug. 
Being a fork of Sourceforge, they missed the changes I did to jmespadero/coindesigner.

**Comment by foobarbecue** [comment]
I see. First of all, thanks for this awesome project! As far as I can tell, it's sill the best free OpenInventor scene graph tool available.

Thanks for clarifying the situation. I see now that the iocroblab readme does explain that it's a fork of this version. I might try and combine the changes on these two forks.

Worth noting that I was using the sourceforge version for years and only just thought to search github recently. I think it would be quite helpful for people if you could have the sourceforge page link to this github.

Closing since you answered my questions!

P.S. Coin3D development isn't dead! It's slow... but at least they are still fixing things.

**Comment by jmespadero** [comment]
Thanks you for let me know you a are still using coindesigner and openinventor, which was one great scene library for the time. I don't know why they didn't launch an official interface like coindesigner because it would helped the beginners to understand the scenegraph. Also, Coindesigner version 1.0 was released in 2005, and that's before the first presentation of Unity. 

I remember doing several enhancement after the move to github. For example, adapt to build with cmake, changes in the help system and several scene simplification routines, like "promote node"
